// Generates land.js: a compact bitmask of land dots sampled on an equal-area-ish grid, so the site needs no map library at runtime.
// Usage: node tools/build-land.mjs [step_in_degrees]
import { writeFileSync } from 'node:fs';

const STEP = Number(process.argv[2] ?? 1.5);
const topo = await (await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json')).json();

const { scale: [sx, sy], translate: [tx, ty] } = topo.transform;
const arcs = topo.arcs.map((arc) => {
  let x = 0, y = 0;
  return arc.map(([dx, dy]) => [(x += dx) * sx + tx, (y += dy) * sy + ty]);
});
const ring = (ids) => ids.flatMap((i) => (i < 0 ? [...arcs[~i]].reverse() : arcs[i]));

const rings = [];
for (const g of topo.objects.land.geometries) {
  const polys = g.type === 'Polygon' ? [g.arcs] : g.arcs;
  for (const p of polys) for (const r of p) {
    const pts = ring(r);
    const xs = pts.map((q) => q[0]), ys = pts.map((q) => q[1]);
    rings.push({ pts, x0: Math.min(...xs), x1: Math.max(...xs), y0: Math.min(...ys), y1: Math.max(...ys) });
  }
}

const inside = (x, y) => {
  let c = false;
  for (const r of rings) {
    if (x < r.x0 || x > r.x1 || y < r.y0 || y > r.y1) continue;
    const p = r.pts;
    for (let i = 0, j = p.length - 1; i < p.length; j = i++) {
      if ((p[i][1] > y) !== (p[j][1] > y) && x < ((p[j][0] - p[i][0]) * (y - p[i][1])) / (p[j][1] - p[i][1]) + p[i][0]) c = !c;
    }
  }
  return c;
};

// Grid must match the decoder in app.js.
const bits = [];
for (let lat = 90 - STEP / 2; lat > -90; lat -= STEP) {
  const n = Math.max(1, Math.round((360 / STEP) * Math.cos((lat * Math.PI) / 180)));
  for (let j = 0; j < n; j++) bits.push(inside(-180 + ((j + 0.5) * 360) / n, lat) ? 1 : 0);
}
const bytes = new Uint8Array(Math.ceil(bits.length / 8));
bits.forEach((b, i) => b && (bytes[i >> 3] |= 1 << (i & 7)));
const b64 = Buffer.from(bytes).toString('base64');

writeFileSync(new URL('../V1/land.js', import.meta.url), `// Generated by tools/build-land.mjs from Natural Earth 110m (public domain). Do not edit.\nwindow.LAND = { step: ${STEP}, bits: '${b64}' };\n`);
console.log(`land.js: ${bits.filter(Boolean).length} land dots / ${bits.length}, ${b64.length} chars`);
